/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_author_free(a: number): void;
export function author_new(a: number, b: number, c: number, d: number): number;
export function author_fromClient(a: number, b: number, c: number, d: number): number;
export function author_import(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function author_export(a: number, b: number, c: number, d: number): void;
export function author_recover(a: number, b: number, c: number, d: number, e: number): number;
export function author_clone(a: number): number;
export function author_channel_address(a: number, b: number): void;
export function author_announcementLink(a: number, b: number): void;
export function author_is_multi_branching(a: number, b: number): void;
export function author_get_client(a: number): number;
export function author_store_psk(a: number, b: number, c: number, d: number): void;
export function author_get_public_key(a: number, b: number): void;
export function author_send_announce(a: number): number;
export function author_send_keyload_for_everyone(a: number, b: number): number;
export function author_send_keyload(a: number, b: number, c: number, d: number): number;
export function author_send_tagged_packet(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function author_send_signed_packet(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function author_receive_subscribe(a: number, b: number): number;
export function author_receive_unsubscribe(a: number, b: number): number;
export function author_receive_tagged_packet(a: number, b: number): number;
export function author_receive_signed_packet(a: number, b: number): number;
export function author_receive_sequence(a: number, b: number): number;
export function author_receive_msg(a: number, b: number): number;
export function author_receive_msg_by_sequence_number(a: number, b: number, c: number): number;
export function author_syncState(a: number): number;
export function author_fetchNextMsgs(a: number): number;
export function author_fetchNextMsg(a: number): number;
export function author_fetch_prev_msg(a: number, b: number): number;
export function author_fetch_prev_msgs(a: number, b: number, c: number): number;
export function author_genNextMsgAddresses(a: number): number;
export function author_fetch_state(a: number, b: number): void;
export function author_reset_state(a: number, b: number): void;
export function author_store_new_subscriber(a: number, b: number, c: number, d: number): void;
export function author_remove_subscriber(a: number, b: number, c: number, d: number): void;
export function author_remove_psk(a: number, b: number, c: number, d: number): void;
export function __wbg_streamsclient_free(a: number): void;
export function streamsclient_new(a: number, b: number, c: number): number;
export function streamsclient_fromClient(a: number): number;
export function streamsclient_get_link_details(a: number, b: number): number;
export function __wbg_sendoptions_free(a: number): void;
export function __wbg_get_sendoptions_local_pow(a: number): number;
export function __wbg_set_sendoptions_local_pow(a: number, b: number): void;
export function sendoptions_new(a: number, b: number, c: number): number;
export function sendoptions_set_url(a: number, b: number, c: number): void;
export function sendoptions_clone(a: number): number;
export function __wbg_address_free(a: number): void;
export function address_new(a: number, b: number): number;
export function address_channelAddress(a: number): number;
export function address_msgId(a: number): number;
export function address_toMsgIndex(a: number, b: number): void;
export function address_toMsgIndexHex(a: number, b: number): void;
export function address_toString(a: number, b: number): void;
export function address_parse(a: number, b: number, c: number): void;
export function address_copy(a: number): number;
export function __wbg_channeladdress_free(a: number): void;
export function channeladdress_bytes(a: number, b: number): void;
export function channeladdress_hex(a: number, b: number): void;
export function channeladdress_toString(a: number, b: number): void;
export function channeladdress_parse(a: number, b: number, c: number): void;
export function __wbg_msgid_free(a: number): void;
export function msgid_bytes(a: number, b: number): void;
export function msgid_hex(a: number, b: number): void;
export function msgid_toString(a: number, b: number): void;
export function msgid_parse(a: number, b: number, c: number): void;
export function msgid_copy(a: number): number;
export function __wbg_userresponse_free(a: number): void;
export function __wbg_nextmsgaddress_free(a: number): void;
export function __wbg_get_nextmsgaddress_identifier(a: number, b: number): void;
export function __wbg_set_nextmsgaddress_identifier(a: number, b: number, c: number): void;
export function __wbg_get_nextmsgaddress_address(a: number): number;
export function __wbg_set_nextmsgaddress_address(a: number, b: number): void;
export function __wbg_userstate_free(a: number): void;
export function __wbg_cursor_free(a: number): void;
export function userstate_new(a: number, b: number, c: number): number;
export function userstate_link(a: number): number;
export function userstate_seqNo(a: number): number;
export function userstate_branchNo(a: number): number;
export function __wbg_pskids_free(a: number): void;
export function pskids_new(): number;
export function pskids_add(a: number, b: number, c: number, d: number): void;
export function pskids_get_ids(a: number): number;
export function __wbg_publickeys_free(a: number): void;
export function publickeys_new(): number;
export function publickeys_add(a: number, b: number, c: number, d: number): void;
export function publickeys_get_pks(a: number): number;
export function __wbg_message_free(a: number): void;
export function message_default(): number;
export function message_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function message_get_identifier(a: number, b: number): void;
export function message_get_public_payload(a: number): number;
export function message_get_masked_payload(a: number): number;
export function nextmsgaddress_new(a: number, b: number, c: number): number;
export function userresponse_new(a: number, b: number, c: number): number;
export function userresponse_fromStrings(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function userresponse_copy(a: number): number;
export function userresponse_link(a: number): number;
export function userresponse_seqLink(a: number): number;
export function userresponse_message(a: number): number;
export function __wbg_details_free(a: number): void;
export function details_get_metadata(a: number): number;
export function details_get_milestone(a: number): number;
export function __wbg_messagemetadata_free(a: number): void;
export function __wbg_get_messagemetadata_is_solid(a: number): number;
export function __wbg_set_messagemetadata_is_solid(a: number, b: number): void;
export function __wbg_get_messagemetadata_referenced_by_milestone_index(a: number, b: number): void;
export function __wbg_set_messagemetadata_referenced_by_milestone_index(a: number, b: number, c: number): void;
export function __wbg_get_messagemetadata_milestone_index(a: number, b: number): void;
export function __wbg_set_messagemetadata_milestone_index(a: number, b: number, c: number): void;
export function __wbg_get_messagemetadata_ledger_inclusion_state(a: number): number;
export function __wbg_set_messagemetadata_ledger_inclusion_state(a: number, b: number): void;
export function __wbg_get_messagemetadata_conflict_reason(a: number): number;
export function __wbg_set_messagemetadata_conflict_reason(a: number, b: number): void;
export function __wbg_get_messagemetadata_should_promote(a: number): number;
export function __wbg_set_messagemetadata_should_promote(a: number, b: number): void;
export function __wbg_get_messagemetadata_should_reattach(a: number): number;
export function __wbg_set_messagemetadata_should_reattach(a: number, b: number): void;
export function messagemetadata_message_id(a: number, b: number): void;
export function messagemetadata_get_parent_message_ids(a: number): number;
export function __wbg_milestoneresponse_free(a: number): void;
export function __wbg_get_milestoneresponse_index(a: number): number;
export function __wbg_set_milestoneresponse_index(a: number, b: number): void;
export function __wbg_get_milestoneresponse_timestamp(a: number, b: number): void;
export function __wbg_set_milestoneresponse_timestamp(a: number, b: number, c: number): void;
export function milestoneresponse_message_id(a: number, b: number): void;
export function channeladdress_copy(a: number): number;
export function userstate_identifier(a: number, b: number): void;
export function sendoptions_url(a: number, b: number): void;
export function __wbg_subscriber_free(a: number): void;
export function subscriber_new(a: number, b: number, c: number): number;
export function subscriber_fromClient(a: number, b: number, c: number): number;
export function subscriber_import(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function subscriber_clone(a: number): number;
export function subscriber_channel_address(a: number, b: number): void;
export function subscriber_announcementLink(a: number, b: number): void;
export function subscriber_get_client(a: number): number;
export function subscriber_is_multi_branching(a: number, b: number): void;
export function subscriber_store_psk(a: number, b: number, c: number, d: number): void;
export function subscriber_get_public_key(a: number, b: number): void;
export function subscriber_author_public_key(a: number, b: number): void;
export function subscriber_is_registered(a: number, b: number): void;
export function subscriber_unregister(a: number, b: number): void;
export function subscriber_export(a: number, b: number, c: number, d: number): void;
export function subscriber_receive_announcement(a: number, b: number): number;
export function subscriber_receive_keyload(a: number, b: number): number;
export function subscriber_receive_tagged_packet(a: number, b: number): number;
export function subscriber_receive_signed_packet(a: number, b: number): number;
export function subscriber_receive_sequence(a: number, b: number): number;
export function subscriber_receive_msg(a: number, b: number): number;
export function subscriber_receive_msg_by_sequence_number(a: number, b: number, c: number): number;
export function subscriber_send_subscribe(a: number, b: number): number;
export function subscriber_send_unsubscribe(a: number, b: number): number;
export function subscriber_send_tagged_packet(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function subscriber_send_signed_packet(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function subscriber_syncState(a: number): number;
export function subscriber_fetchNextMsgs(a: number): number;
export function subscriber_fetchNextMsg(a: number): number;
export function subscriber_fetch_prev_msg(a: number, b: number): number;
export function subscriber_fetch_prev_msgs(a: number, b: number, c: number): number;
export function subscriber_genNextMsgAddresses(a: number): number;
export function subscriber_fetch_state(a: number, b: number): void;
export function subscriber_reset_state(a: number, b: number): void;
export function subscriber_remove_psk(a: number, b: number, c: number, d: number): void;
export function set_panic_hook(): void;
export function __wbg_addressgetter_free(a: number): void;
export function addressgetter_new(a: number, b: number, c: number): number;
export function addressgetter_accountIndex(a: number, b: number, c: number): void;
export function addressgetter_range(a: number, b: number, c: number, d: number): void;
export function addressgetter_bech32Hrp(a: number, b: number, c: number, d: number): void;
export function addressgetter_includeInternal(a: number, b: number): void;
export function addressgetter_get(a: number, b: number): void;
export function __wbg_messagegetter_free(a: number): void;
export function messagegetter_new(a: number): number;
export function messagegetter_index(a: number, b: number, c: number, d: number): void;
export function messagegetter_data(a: number, b: number, c: number, d: number): void;
export function messagegetter_raw(a: number, b: number, c: number, d: number): void;
export function messagegetter_children(a: number, b: number, c: number, d: number): void;
export function messagegetter_metadata(a: number, b: number, c: number, d: number): void;
export function __wbg_client_free(a: number): void;
export function client_message(a: number): number;
export function client_getAddresses(a: number, b: number, c: number): number;
export function client_getUnspentAddress(a: number, b: number, c: number): number;
export function client_getBalance(a: number, b: number, c: number): number;
export function client_getAddress(a: number): number;
export function client_getInfo(a: number, b: number): void;
export function client_getNodeInfo(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function client_networkInfo(a: number, b: number): void;
export function client_getNetworkId(a: number, b: number): void;
export function client_getBech32Hrp(a: number, b: number): void;
export function client_getMinPowScore(a: number, b: number): void;
export function client_getHealth(a: number, b: number): void;
export function client_getTips(a: number, b: number): void;
export function client_getPeers(a: number, b: number): void;
export function client_getOutput(a: number, b: number, c: number, d: number): void;
export function client_findMessages(a: number, b: number, c: number, d: number): void;
export function client_findInputs(a: number, b: number, c: number, d: number, e: number): void;
export function client_findOutputs(a: number, b: number, c: number, d: number): void;
export function client_getAddressBalances(a: number, b: number, c: number): void;
export function client_getMilestone(a: number, b: number, c: number): void;
export function client_getMilestoneUtxoChanges(a: number, b: number, c: number): void;
export function client_getReceipts(a: number, b: number): void;
export function client_getReceiptsMigratedAt(a: number, b: number, c: number): void;
export function client_getTreasury(a: number, b: number): void;
export function client_getIncludedMessage(a: number, b: number, c: number, d: number): void;
export function client_postMessage(a: number, b: number, c: number): void;
export function client_retry(a: number, b: number, c: number, d: number): void;
export function client_retryUntilIncluded(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function client_reattach(a: number, b: number, c: number, d: number): void;
export function client_promote(a: number, b: number, c: number, d: number): void;
export function client_consolidateFunds(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function client_bech32ToHex(a: number, b: number, c: number, d: number): void;
export function client_hexToBech32(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function client_hexPublicKeyToBech32Address(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function client_isAddressValid(a: number, b: number, c: number): number;
export function client_generateMnemonic(a: number, b: number): void;
export function client_mnemonicToHexSeed(a: number, b: number, c: number, d: number): void;
export function client_getMessageId(a: number, b: number, c: number, d: number): void;
export function client_getTransactionId(a: number, b: number, c: number, d: number): void;
export function client_getMessage(a: number): number;
export function __wbg_getaddressbuilder_free(a: number): void;
export function getaddressbuilder_new(a: number): number;
export function getaddressbuilder_balance(a: number, b: number, c: number, d: number): void;
export function getaddressbuilder_outputs(a: number, b: number, c: number, d: number, e: number): void;
export function start(): void;
export function __wbg_balancegetter_free(a: number): void;
export function balancegetter_new(a: number, b: number, c: number): number;
export function balancegetter_accountIndex(a: number, b: number, c: number): void;
export function balancegetter_initialAddressIndex(a: number, b: number, c: number): void;
export function balancegetter_gap_limit(a: number, b: number, c: number): void;
export function balancegetter_get(a: number, b: number): void;
export function __wbg_clientbuilder_free(a: number): void;
export function clientbuilder_new(): number;
export function clientbuilder_node(a: number, b: number, c: number, d: number): void;
export function clientbuilder_primaryNode(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function clientbuilder_primaryPowNode(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function clientbuilder_permanode(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function clientbuilder_nodeAuth(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function clientbuilder_nodes(a: number, b: number, c: number): void;
export function clientbuilder_nodeSyncInterval(a: number, b: number, c: number): void;
export function clientbuilder_nodeSyncDisabled(a: number, b: number): void;
export function clientbuilder_offlineMode(a: number, b: number): void;
export function clientbuilder_nodePoolUrls(a: number, b: number, c: number): void;
export function clientbuilder_quorum(a: number, b: number, c: number): void;
export function clientbuilder_quorumSize(a: number, b: number, c: number): void;
export function clientbuilder_quorumThreshold(a: number, b: number, c: number): void;
export function clientbuilder_network(a: number, b: number, c: number, d: number): void;
export function clientbuilder_localPow(a: number, b: number, c: number): void;
export function clientbuilder_tipsInterval(a: number, b: number, c: number): void;
export function clientbuilder_requestTimeout(a: number, b: number, c: number): void;
export function clientbuilder_apiTimeout(a: number, b: number, c: number, d: number, e: number): void;
export function clientbuilder_build(a: number, b: number): void;
export function __wbg_unspentaddressgetter_free(a: number): void;
export function unspentaddressgetter_new(a: number, b: number, c: number): number;
export function unspentaddressgetter_accountIndex(a: number, b: number, c: number): void;
export function unspentaddressgetter_initialAddressIndex(a: number, b: number, c: number): void;
export function unspentaddressgetter_get(a: number, b: number): void;
export function __wbg_messagebuilder_free(a: number): void;
export function messagebuilder_new(a: number): number;
export function messagebuilder_index(a: number, b: number, c: number, d: number): void;
export function messagebuilder_data(a: number, b: number, c: number, d: number): void;
export function messagebuilder_seed(a: number, b: number, c: number, d: number): void;
export function messagebuilder_accountIndex(a: number, b: number, c: number): void;
export function messagebuilder_initialAddressIndex(a: number, b: number, c: number): void;
export function messagebuilder_parents(a: number, b: number, c: number): void;
export function messagebuilder_input(a: number, b: number, c: number, d: number): void;
export function messagebuilder_inputRange(a: number, b: number, c: number, d: number): void;
export function messagebuilder_output(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function messagebuilder_dustAllowanceOutput(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function messagebuilder_prepareTransaction(a: number, b: number): void;
export function messagebuilder_signTransaction(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function messagebuilder_finishMessage(a: number, b: number, c: number): void;
export function messagebuilder_submit(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h45c87d7cad3bb951(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hd67b012b38ff8c15(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h943e05907d25c2a8(a: number, b: number, c: number, d: number): void;
export function __wbindgen_start(): void;
