name: tcli Test

on:
  push:
    branches: ["main"]
    paths:
      - "tools/tangle-cli/**"
      - ".github/workflows/tcli-test.yaml"
  pull_request:
    types: [opened, synchronize]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm 8
        run: npm install -g npm@8
      - name: Tool code build
        run: |
          npm install
          npm run build-esm
          npm run package-esm
          npm run build-anchors
          npm run package-anchors
          npm run build-tcli
